### ISSUE TITLE
Breaks when used with injectable

### ISSUE THREAD

**Issue by lukepighetti** [marcglasberg/i18n_extension#30] opened 2020-04-20 00:19 UTC
Whenever I try to use this package with `injectable` I get this error

```
NoSuchMethodError: The getter 'major' was called on null.
Receiver: null
Tried calling: major
[SEVERE] injectable_generator:injectable_builder on test/widget_test.dart:
```

https://github.com/Milad-Akarie/injectable/issues/51

**Comment by marcglasberg** [comment] 2020-04-20 16:20
I don't use this injectable package, so it's difficult for me to understand what the problem is. I'd say, however, it seems at first glance that to solve this problem something must be changed in the injectable package end, not in i18n_extension.

If I do need to change something in i18n_extension, then you or the injectable package's maintainer must tell me what exactly.

**Comment by lukepighetti** [comment] 2020-04-20 19:15
I decided to open mirroring issues on both packages. If you feel there is nothing on your end to change I am personally fine with you closing this issue.

**Comment by marcglasberg** [comment] 2020-04-21 01:25
Ok, so I'll close this. If somehow it turns out I was wrong and must change something here, just let me know.

**Closed by marcglasberg** 2020-04-21 01:25 UTC
