### ISSUE TITLE
Could not find bin/getstrings.dart in package i18n_extension.

### ISSUE THREAD

**Issue by chriscdn** [marcglasberg/i18n_extension#135] opened 2023-10-19 19:49 UTC
The `README.md` states:

> Simply run `flutter pub run i18n_extension:getstrings` in your project root directory and you will get a list of strings to translate in `strings.json`. 

When running this I get the following error:

> Could not find `bin/getstrings.dart` in package `i18n_extension`.

I'm using i18n_extension v9.0.2.

**Comment by marcglasberg** [comment] 2023-10-19 22:13
Closing as duplicate of https://github.com/marcglasberg/i18n_extension/issues/126 and https://github.com/marcglasberg/i18n_extension/issues/132

**Closed by marcglasberg** 2023-10-19 22:13 UTC
