### ISSUE TITLE
Error on import package:i18n_extension/io/import.dart in version 9.0.0

### ISSUE THREAD

**Issue by ruben69695** [marcglasberg/i18n_extension#133] opened 2023-05-18 16:58 UTC
Hi, I migrated the package from version **5.0.1** to **9.0.0** and since this, now I see an error in dart code when importing that reference, I see in the main branch that the directory **"io"** is not anymore. What happened with this? I 've been using this for importing my .po translation files. Is the importing system not supported anymore? 🫠

Thanks! 😄

**Comment by Namli1** [comment] 2023-05-19 10:07
I have the same problem, I used to import the `GettextImporter()` like this:
```dart
import 'package:i18n_extension/io/import.dart';
```
But it seems like the file has been moved, it now seems to be at [`test/getStrings/io/import.dart`](https://github.com/marcglasberg/i18n_extension/blob/master/test/getStrings/io/import.dart).
I don't know how to import that, I don't even know if it's possible to import files from the `/test` folder.

**Comment by marcglasberg** [comment] 2023-05-29 19:44
I am closing this as a duplicate of https://github.com/marcglasberg/i18n_extension/issues/132

Please see the problem here https://github.com/marcglasberg/i18n_extension/issues/126 and help fix this if you can. Thank you!

Meanwhile, the `JSONImporter` is in the `i18n_extension\test\getStrings` directory of this repo. I suggest you copy it from there, and run it.

**Closed by marcglasberg** 2023-05-29 19:44 UTC
