### ISSUE TITLE
Where to put the I18n widget in relation to MaterialApp

### ISSUE THREAD

**Issue by q876625596** [marcglasberg/i18n_extension#10] opened 2020-01-16 03:17 UTC
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'data' was called on null.
Receiver: null
Tried calling: data

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      I18n.of (package:i18n_extension/i18n_widget.dart:74:73)
#2      ShopAddMenu.build.<anonymous closure> (package:jtw_app_flutter/ui/entertainment/entertainmentHome/shopPublish/shopAddMenu/shop_add_menu.dart:55:16)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#8c92c
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(398.0, 52.8)
  finalLocalPosition: Offset(33.6, 28.8)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by q876625596** [comment] 2020-01-16 03:18
``` dart
  static _I18nState of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<_InheritedI18n>().data;
  }
```
'context.dependOnInheritedWidgetOfExactType<_InheritedI18n>()'  is null

**Comment by marcglasberg** [comment] 2020-01-16 16:40
Can you please provide me with some minimum runnable code (with main method and all) demonstrating the problem? I need to reproduce it to be able to fix it.

**Comment by marcglasberg** [comment] 2020-01-20 22:06
@q876625596  Could you please upgrade to version 1.3.0 and tell me if it solved your problem?

Please note, in this new version you cannot do Locale("pt_BR") anymore, since this is actually the wrong way to create a locale. You must do Locale("pt", "BR").

**Comment by ManojMM026** [comment] 2020-01-22 07:28
This issue is still there in 1.3.0, also How do we change locale of entire flutter app? 
I am trying to change locale from my settings page

**Comment by marcglasberg** [comment] 2020-01-22 18:49
Ok. You still need to provide me with some minimum runnable code (with main method and all) demonstrating the problem. I need to reproduce it to be able to fix it.

**Comment by ManojMM026** [comment] 2020-01-23 05:39
I think It will be great if you write sample app which shows how to change locale of entire app using i18n_extension.

**Comment by marcglasberg** [comment] 2020-01-24 01:51
You already have this in the included `example` directory:

         https://github.com/marcglasberg/i18n_extension/tree/master/example/lib

You must run `main.dart` there.

**Comment by EducatedDeer** [comment] 2020-02-12 12:42
As i see it, it(manually changing languages) only works on the main page. When i make a Settings page or When i make a alertdialog to change to different languages it gives the same error above.
Example app only has 1 screen.

**Comment by marcglasberg** [comment] 2020-02-13 15:38
Can you please provide me with some minimum runnable code (with main method and all) demonstrating the problem? I need to reproduce it to be able to fix it.

Please follow these guidelines: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by EducatedDeer** [comment] 2020-02-13 19:09
------------------------------------------
Same code as Example:
just added a button to my_screen.dart and a change language page
----------------------------------------------
`RaisedButton(
            child: Text("Language Test"),
            onPressed:(){
            Navigator.push(context, MaterialPageRoute(builder: (context) => ChangeLang()));
          } ,),`

-------------------------------------------
Change Language page
---------------------------
import 'package:flutter/material.dart';
import 'package:i18n_extension/i18n_widget.dart';

class ChangeLang extends StatefulWidget {
  @override
  _ChangeLangState createState() => _ChangeLangState();
}

class _ChangeLangState extends State<ChangeLang> {
  @override
  Widget build(BuildContext context) {
    return I18n(
          child: Column(
        children: <Widget>[
          RaisedButton(onPressed: (){
          setState(() {I18n.of(context).locale = Locale("pt", "BR");});
        },child: Text("PT")),
        RaisedButton(onPressed: (){
          setState(() {I18n.of(context).locale = Locale("en", "US");});
        },child: Text("EN")),
        ], 
      ),
    );
  }
}

**Comment by RenanDelfanti** [comment] 2020-02-26 18:41
I got same error.

**Comment by marcglasberg** [comment] 2020-02-26 18:51
@EducatedDeer Please post here a complete example code, as simple as possible to demonstrate the problem, for a single file including a main method.

Please follow these guidelines: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by RenanDelfanti** [comment] 2020-02-26 19:02
@marcglasberg  In my case, I found that I needed to use the i18n widget above the provider's widget.

**Comment by Christian-Martensson** [comment] 2020-03-04 18:09
Hi! 
I'd like to add to this issue, as I spent hours struggling with it. What @RenanDelfanti said works. Instead of placing the I18n wrapper widget after the MaterialApp widget, I put it as the first widget in the widget tree. This solved the problem for me. I see the problem was not thoroughly explained in this thread. For me it was like this: 

I have a preferences page which can be navigated to through a drawer and Navigator.push() method. While this pref page was in the drawer, and I navigated to it and changed language, I would get the same error: 
`I18n.of(context) NoSuchMethodError: The getter 'data' was called on null. `

However, if I put the preferences page directly into the home page of the app (the page that opens at start up), the language switching works flawlessly. By moving the I18n wrapper widget to the top of the app, the problem was fixed.

I18n(child: MaterialApp())
It would be great if you could update the documentation and example app to reflect this change, i.e. so that the I18n widget is moved further up the widget tree. Thank you kindly for this amazing package, it is much better than the current alternatives for flutter!

**Comment by crizant** [comment] 2020-03-08 07:55
I would like to point out a few things here:
1. The `Locale` object should be created by `Locale('pt', 'br')` not `Locale('pt_BR')`
2. The `I18n.of(context).locale = Locale("pt", "br")` statement don't need to wrap inside a `setState()` call.
3. If you have a `home` parameter in the `MaterialApp` widget, you may put the `I18n` there, just like the example.
But if you handle your routes with a `routes` map, you may wrap your `MaterialApp` inside `I18n` like:

```dart
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return I18n(
        child: MaterialApp(
          routes: routes,
          initialRoute: '/',
        ),
      ),
    );
  }
}
```

**Comment by doc-rj-celltrak** [comment] 2020-03-26 20:30
@crizant Great clarification in point 3.

**Comment by QLaille** [comment] 2020-04-20 14:41
Just in case I would like to confirm that what @Christian-Martensson and @RenanDelfanti suggested works !

**Comment by manualfromcolumbia** [comment] 2020-06-05 01:49
Just wanted to know if anyone has any issues when wrapping the `MaterialApp` inside `I18n` (when handling routes).

When I run the example where the `I18n` is wrapping a child in the `home` parameter, and the iOS simulator has Spanish as the default language, it works.

But when the `I18n` wraps the `MaterialApp` the default locale is en_us. Is ignoring the current system locale.

**Comment by crizant** [comment] 2020-06-05 07:17
> Just wanted to know if anyone has any issues when wrapping the `MaterialApp` inside `I18n` (when handling routes).
> 
> When I run the example where the `I18n` is wrapping a child in the `home` parameter, and the iOS simulator has Spanish as the default language, it works.
> 
> But when the `I18n` wraps the `MaterialApp` the default locale is en_us. Is ignoring the current system locale.

Yes, that's why I have implemented a splash screen to detect the language:
```dart
  @override
  void afterFirstLayout(BuildContext context) async {
    await _detectLocale();
    Navigator.of(context).pushReplacementNamed('/login');
  }

  void _detectLocale() async {
    // default locale of the app
    Locale selectedLocale = Locale('en');
    // locale of the device 
    final Locale deviceLocale = Localizations.localeOf(context);

    // get stored locale (from local storage or anything if you want), and check if it is valid
    // if not, see if device locale is supported by the app
    // just find a proper locale and assign it to `selectedLocale`
    // ...

    // finally, set the selected locale of the app
    I18n.of(context).locale = selectedLocale;
  }
```

p.s.: To have the `afterFirstLayout` method, you need to use this package: [`after_layout`](https://pub.dev/packages/after_layout)

**Comment by hlemcke** [comment] 2020-11-23 19:42
The best approach would be that `I18n` uses a given locale with a fallback to use the best matching device locale. This requires `I18n` to also accept `supportedLocales` as `MaterialApp` does.

Example (shortened to use only language code):
* device locales = `[nl, de, en]`
* supported locales = `[en, de]`
* I18n should resolve to `de` (not `en` and for sure not `nl`) unless the user has chosen `de` in some app internal preferences

This can be achieved when:
1. the locale to use (lets call it `thisAppsLocale`) is determined before building `MaterialApp` and `I18n`
1. `thisAppsLocale` is used by: `Localizations, I18n` and also `intl`
1. `thisAppsLocale` can be updated by some app internal selection (e.g. DropdownButton) and also when the user changes the list of device locales 

Possible solution:
```
class MyApp extends StatefulWidget {
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
final List<Locale> supportedLocales = [
    Locale('en', 'US'),
    Locale('de', 'DE'),
  ];
Locale thisAppsLocale;

void initState() {
    thisAppsLocale = resolveLocale(null);
    super.initState();
}

Widget build( BuildContext context) {
  Intl.defaultLocale = thisAppsLocale.toString();
  return MaterialApp(
    home: I18n(
      child: MyHomePage(),
      locale: thisAppsLocale,    // see enhancement request https://github.com/marcglasberg/i18n_extension/issues/55
      useLanguageOnly: true, ),   // see enhancement request https://github.com/marcglasberg/i18n_extension/issues/54
    locale: thisAppsLocale,
    localeListResolutionCallback: (_, __) => localeResolutionCallback(),
      localizationsDelegates: [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
              ],
              supportedLocales: DjarjoLocale.supportedLocales, ); }

/// Resolves to use best matching locale.
/// TODO enhance method to try language codes if no full match found
Locale resolveLocale( Locale newLocale ) {
  List<Locale> deviceLocales = WidgetsBinding.instance.window.locales;  // always use most current list
  if ( supportedLocales.contains( newLocale)) { return newLocale; }
  for ( Locale devLoc in deviceLocales ) {
    if ( supportedLocales.contains( devLoc )) {return devLoc; }
  }
  return supportedLocales[0]; // Fallback if nothing found
}

Locale localeResolutionCallback() {
  Locale newLoc = resolve( null );
  setThisAppsLocale( newLoc );
  return newLoc;
}

/// Setter method 
void setThisAppsLocale( Locale newLocale ) {
    Locale locToSet = resolveLocale(newLocale);
    if (thisAppsLocale != locToSet) {
      setState(() => thisAppsLocale = locToSet);
    }
}
```

**Comment by LaysDragon** [comment] 2022-03-08 10:48
yeah...We really need a good way to integrate I18nWidget with MaterialApp route,or there just a big hole here,since developing flutter App without route isn't unrealistic.

**Comment by LaysDragon** [comment] 2022-03-08 11:43
I found another way to implemented system language detecting without putting it inside any screen widget,by insert logic into the localeListResolutionCallback of Material. Its seems not the best but atleast its works for me.

```dart
return MaterialApp(
      localeListResolutionCallback: (locales, supportedLocales) {
        // get locale from flutter's default locale resolution function
        var locale = basicLocaleListResolution(locales, supportedLocales);
        // overwrite default locale
        I18n.defaultLocale = locale;
        // and this one triggered rebuilding
        Future.microtask(() => I18n.of(context).locale = locale);
        return locale;
      },
      ...
}
```

**Comment by k2s** [comment] 2023-03-24 23:43
My solution with router (go_router) and provider (riverpod).
Should work also with `I18n.of(context).locale` without using of provider.


```dart
    final Locale? appLanguage = ref.watch(appLanguageProvider);

    return MaterialApp.router(
      builder: (context, child) {
        // the child here is the Router and context is already available
        // also the localeListResolutionCallback method was already evaluated
        return I18n(initialLocale: appLanguage, child: child!);
      },
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
//      ...
```

**Comment by marcglasberg** [comment] 2024-12-12 20:57
@q876625596 
@ManojMM026
@EducatedDeer
@RenanDelfanti
@Christian-Martensson
@crizant
@doc-rj-celltrak
@QLaille
@manualfromcolumbia
@hlemcke
@RaulUrtecho
@LaysDragon
@k2s

Version **14.0.0-dev** fixes this once and for all. Please check the CHANGELOG.

---

## 14.0.0-dev.1

Version 14 brings important improvements, like new interpolation methods, useful
extensions, and improved standardization, with the cost of a few breaking changes that
are easy to fix. Please, follow the instructions below to upgrade your code.

* **Breaking Change**: Now, you must have a single (no more than one) `I18n` widget in
  your entire widget tree, and it must always be put ABOVE the `MaterialApp`
  (or `CupertinoApp`) widget, in the tree. There, it will be able to provide translations
  to all your routes and dialogs.


* **Breaking Change**: You must now add the line `locale: I18n.locale` to your
  `MaterialApp` (or `CupertinoApp`) widget, like this:

  ```
  MaterialApp(
     locale: I18n.locale,
     ...      
  ``` 


* **Breaking Change**: Because of the way Flutter works, you have to make sure your `I18n`
  widget is NOT declared in the same widget as the `MaterialApp`, but in a **parent**
  widget. For example, this is WRONG:

  ```dart
  Widget build(BuildContext context) {
    return I18n( // Wrong!
      child: MaterialApp(
        home: MyScreen(),
  ```        

  Instead, this is how your `main.dart` file could look like:

  ```dart    
  import 'package:i18n_extension/i18n_extension.dart';
  import 'package:flutter_localizations/flutter_localizations.dart';
         
  void main() {
    WidgetsFlutterBinding.ensureInitialized();
    runApp(MyApp());
  }
  
  class MyApp extends StatelessWidget {
    Widget build(BuildContext context) {
      return I18n( // I18n in a parent widget!
        child: AppCore(),
      );
    }
  }
  
  class AppCore extends StatelessWidget {
    Widget build(BuildContext context) {
      return MaterialApp( // MaterialApp is here!
        locale: I18n.locale, // Locale declaration is here!
        localizationsDelegates: [ ... ],
        supportedLocales: [ ... ],
        home: ...
      ),
  ```  

  Another good alternative is declaring the `I18n` widget directly inside the `runApp`
  call, in your `main` function:

  ```dart    
  void main() {
    WidgetsFlutterBinding.ensureInitialized();
    runApp(I18n(child: AppCore())); // I18n in a parent widget!
  }
  
  class AppCore extends StatelessWidget {
    Widget build(BuildContext context) {
      return MaterialApp( // MaterialApp is here!
        locale: I18n.locale, // Locale declaration is here!
        localizationsDelegates: ...
      ),
  ```  


* **Breaking Change**: The `MaterialApp` (or `CupertinoApp`) widget contains, internally,
  a `Localizations` widget, which is used by Flutter to provide translations to all native
  Flutter widgets.
  The `I18n` widget will now automatically keep in sync with this `Localizations` widget,
  so that when you change the locale in `I18n` (with `context.locale = 'en-US'.asLocale`,
  for example), it will also change automatically in the `Localizations` widget. This
  means that `Localizations.of(context).locale` will always return the same result as
  `I18n.of(context).locale`, as `context.locale`, and as `I18n.locale`.

  If you previously had your own logic to change the native `Localizations` locale by
  changing the `locale` parameter of the `MaterialApp` widget, you can now remove it,
  as this is not necessary anymore.


* **Breaking Change**: Language codes must now respect the BCP47 standard, when you
  define your translations.  
  For example, you should now use `en-US` instead of the old `en_us` format.
  Other valid code examples are: `en`, `es-419`, `hi-Deva-IN` and `zh-Hans-CN`.

  This is an example of a WRONG translation definition:

  ```dart     
  // Will throw: Locale "en_us" should be "en-US" 
  Translations.byText('en_us') + // Wrong!
     {
        'en_us': 'Hello, how are you?',  // Wrong!
        'pt_br': 'Olá, como vai você?',  // Wrong!
        'es': '¿Hola! Cómo estás?',
        'fr': 'Salut, comment ca va?',
        'de': 'Hallo, wie geht es dir?',
     };
  ```                                                                          

  To help you upgrade, a `TranslationsException` error will be thrown when you use the
  old code format. The error message will be something like:
  `Locale "en_us" should be "en-US"`

  This is an example of a VALID and correct translation definition:

  ```dart
  Translations.byText('en-US') +
     {
        'en-US': 'Hello, how are you?',
        'pt-BR': 'Olá, como vai você?',
        'es': '¿Hola! Cómo estás?',
        'fr': 'Salut, comment ca va?',
        'de': 'Hallo, wie geht es dir?',
     };
  ```

  Note: If your translations are defined manually in the code, you can quickly fix this
  by doing a few _Search and Replace_ commands in your IDE to fix the language codes, one
  for each of your supported languages, for example, replacing `'en_us'` with `'en-US'`
  etc.


* New extension `Locale.format` can be used to return the string representation of the
  Locale as a valid BCP47 language tag (compatible with the Unicode Locale Identifier
  (ULI) syntax). If the locale is not valid, `format` may return an invalid tag, or may
  return string "und" (undefined).  
  The language code, script code, and country code will be separated by a hyphen,
  and any lowercase/uppercase issues will be fixed. For example:

  ```dart
  var locale = Locale('en', 'us');
  print(locale.format()); // en-US, which is a valid BCP47 language tag
  print(locale.toString()); // en_US
  print(locale.toLanguageTag()); // en-us
  ```

  Using `format` is recommended over `toString` and `toLanguageTag` (both natively
  provided by the `Locale` class). In more detail:

    - `Locale.format()` returns the string representation of the Locale as a valid BCP47
      language tag, fixing any lowercase/uppercase issues and separating components with
      a hyphen. Allows specifying a different separator. For example,
      `Locale('en', 'us').format()` returns `en-US`, and
      `Locale('en', 'US').format(separator: '|')` returns `en|US`.

    - `Locale.toString()` returns the language, script and country codes separated by an
      underscore. For example, `Locale('en', 'us').toString()` returns `en_us`
      and `Locale('en', 'US').toString()` returns `en_US`.

    - `Locale.toLanguageTag()` returns the language code and the country code separated by
      a hyphen, but does not fix case. For example, `Locale('en', 'us').toLanguageTag()`
      returns `en-us`, and `Locale('en', 'US').toLanguageTag()` returns `en-US`.


* New extension `String.asLocale` can be used to convert a `String` containing a BCP47
  language tag to a `Locale` object. For example: `Locale locale = 'pt-BR'.asLocale;`.
  If the string is not a valid BCP47 language, `asLocale` will try to fix it.
  For example, the following lines are all **equivalent** and result in the same locale:

  ```dart
  var locale = Locale('en', 'US'); 
  var locale = 'en-US'.asLocale; 
  var locale = 'en_US'.asLocale; 
  var locale = 'en-us'.asLocale; 
  var locale = 'EN-US'.asLocale; 
  var locale = 'en US'.asLocale; 
  var locale = 'en|US'.asLocale; 
  var locale = 'en.uS'.asLocale; 
  var locale = 'eN,US'.asLocale; 
  var locale = 'en;US'.asLocale; 
  var locale = 'en, US'.asLocale; 
  ```

  However, it will only fix the most common errors, by fixing lowercase/uppercase issues,
  removing spaces, and converting all these separators: `-` `_` ` ` `|` `.` `,` `;` to
  hyphens. If it can’t fix it, it will return an invalid `Locale`, or maybe
  `Locale('und')`, meaning the locale is undefined.

  Note that `String.asLocale` can be used whenever you previously used Locale
  constructors. For example, instead of:

  ```dart
  supportedLocales: [
    Locale('en', 'US'),
    Locale('es', 'ES'),
  ],
  ```

  You can now write:

  ```dart
  supportedLocales: [
    'en-US'.asLocale,
    'es-ES'.asLocale,    
  ],
  ```


* New extension `String.asLanguageTag` can be used to try and normalize String language
  tags to the BCP47 standard (which is compatible with the Unicode Locale Identifier
  (ULI) syntax). It fixes casing (uppercase and lowercase), removes spaces, and turns
  underscores into hyphens. As such, it can be used to convert the old format language
  tags to the new ones. For example: `'en_us'.asLanguageTag` returns `'en-US'`.


* **Interpolations.** You can now do string interpolations by replacing placeholders with
  values, with the `args` function:

  ```dart
  // Hello John and Mary
  'Hello {} and {}'.i18n.args('John', 'Mary');
  
  // Also works with iterables
  'Hello {} and {}'.i18n.args(['John', 'Mary']);
  
  // Named placeholders
  'Hello {name} and {other}'.i18n.args({'name': 'John', 'other': 'Mary'});
  
  // Numbered placeholders
  'Hello {1} and {2}'.i18n.args({1: 'John', 2: 'Mary'});
  
  // And you can mix placeholder types
  'Hello {name}, let’s meet up with {} and {other} to explore {1} and {2}.'.i18n.args('Charlie', {'name': 'Alice', 'other': 'Bob'}, {1: 'Paris', 2: 'London'});
  ```   

  For all the details, check the README.md file.


* **Breaking Change**: Previously, you could also do string interpolation by using
  **sprintf** specifiers, like `%s`, `%1$s`, `%d` etc., and providing a list of values to
  fill them. This is still supported:

  ```                   
  // Hello John and Mary
  'Hello %s and %s'.i18n.fill(['John', 'Mary']);
  
  // Hello John and Mary
  'Hello %1$s and %2$s'.i18n.fill(['John', 'Mary']);  
  
  // Hello Mary and John  
  'Hello %2$s and %1$s'.i18n.fill(['John', 'Mary']);  
  ```

  However, you can now also provide the values directly, without having to wrap them
  in a list:

  ```
  'Hello %s and %s'.i18n.fill('John', 'Mary');
  'Hello %1$s and %2$s'.i18n.fill('John', 'Mary');
  'Hello %2$s and %1$s'.i18n.fill('John', 'Mary');
  ```

  The breaking change part of it is that, previously, if you wanted to use the `fill`
  extension you needed to declare it yourself in your translations files. Now, that's not
  necessary anymore, as this extension is provided out of the box. For this reason, if you
  declared the `fill` extension yourself, you now need to remove it. Otherwise, the
  compiler will complain that the extension is declared twice. If you still want to keep
  your old declaration, change its name.


* **Auto saving the locale.** Some apps may allow the user to change the language/locale
  of the app, from inside the app. You'd usually create some widget that presents the list
  of available locales, and then set it with `context.locale = 'es-ES'.asLocale;` or
  similar.

  If you want that user choice to be saved between app restarts,
  simply set the `autoSaveLocale` parameter to `true`:

  ```dart
  I18n(
    autoSaveLocale: true,
    child: AppCore(),
    ...
  ```

  This will automatically save changes to the locale in the device's storage
  (shared preferences), and restore it when the app restarts.
  Note the locale is read asynchronously, which may result in a one frame flicker
  of the default system locale, before the saved locale is restored. If you want to avoid
  this flicker, you can explicitly preload the locale yourself by doing
  `initialLocale: await I18n.loadLocale()` when the app starts.

  ```dart    
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();
   
    runApp(
      I18n(
        initialLocale: await I18n.loadLocale(),
        autoSaveLocale: true, 
        child: AppCore(),    
        ...
  ```

  > Note: While usually not needed, you can also manually load, save and delete the
  > locale from the shared preferences, at any later time,
  > by using the provided static functions:
  > `var locale = await I18n.loadLocale()`, `I18n.saveLocale(locale)`
  > and `I18n.deleteLocale()`.


* You can get the current locale by using the `context`:

  ```dart
  Locale locale = context.locale;
  Locale locale = I18n.of(context).locale;
  ```

  However, you can also get the locale **statically**,
  allowing you to use it in non-widget code:

  ```dart
  // Get a `Locale` object, like Locale('en', 'US') 
  Locale locale = I18n.locale;
  
  // Or get a BCP47 language tag string, like 'en-US'
  String languageTag = I18n.languageTag;
  String languageTag = I18n.locale.format();
  
  // Or get a locale string with a specific separator, like 'en|US'
  String languageTag = I18n.locale.format(separator: '|');
  
  // Or get only the lowercase language code part of the locale, like 'en'.
  String language = I18n.language;
  ```

  Note, using `I18n.localeStr` is deprecated. It returns a lowercase string with
  underscores, like `en_us`.


* To change the current locale, do this:

  ```dart
  context.locale = Locale('pt', 'BR');
  
  // Or
  context.locale = 'pt-BR'.asLocale;
  
  // Or
  I18n.of(context).locale = 'pt-BR'.asLocale;
  ```

  To reset the current locale back to the default **system locale**, do this:

  ```dart
  context.locale = null;
  
  // Or
  context.resetLocale();
  
  // Or
  I18n.of(context).locale = null;
  
  // Or
  I18n.of(context).resetLocale();
  ```

  Note, any of the above will change the current locale for your widgets using
  the `i18n_extension`, and also for native Flutter widgets.


* **Breaking Change**: The fallback rules changed a little bit.
  What happens when you don’t provide the translations for the current locale?
  For example, suppose your current locale is Spanish, but you have only provided
  translations for English and French.
  Fallback behavior is now more intuitive and aligned with common sense.
  In most cases, it will do exactly what you’d expect.
  However, if you want all the details, check the README.md file.

**Closed by marcglasberg** 2024-12-12 20:57 UTC
Labels: documentation, enhancement
