### ISSUE TITLE
There are no translations in 'en-UA' for "Some string" error when trying to use 'language code only' locale

### ISSUE THREAD

**Issue by Apollo108** [marcglasberg/i18n_extension#143] opened 2024-12-18 10:18 UTC
Hi, I'm having a _There are no translations in 'en-UA' for "Some string"_ error when trying to use 'language code only' locale.

<img width="699" alt="image" src="https://github.com/user-attachments/assets/1e10a9b3-caf9-483b-8370-6c0ae8df15cb" />
<img width="658" alt="image" src="https://github.com/user-attachments/assets/0577bff4-8151-4d3c-a64b-6533534e3134" />
<img width="583" alt="image" src="https://github.com/user-attachments/assets/5df85f1c-138d-4727-851c-b3df1485741d" />

**Package version: ^14.1.0**

What am I doing wrong?

_Originally posted by @Apollo108 in https://github.com/marcglasberg/i18n_extension/issues/54#issuecomment-2547824848_

**Comment by marcglasberg** [comment] 2024-12-18 18:34
You are not doing anything wrong. Your system is using `en-UA` and it can't find `en-UA`, so it's stating that fact. 

The callbacks I'm using to print this information are just too naïve. Here they are:

```dart
  /// Replace this to log missing keys.
  static void Function(Object? key, StringLocale locale) missingKeyCallback =
      (key, locale) => print('➜ Translation-key in "$locale" is missing: "$key".');

  /// Replace this to log missing translations.
  static void Function(Object? key, StringLocale locale) missingTranslationCallback =
      (key, locale) => print('➜ There are no translations in "$locale" for "$key".');
```

I will fix this.

**Comment by Apollo108** [comment] 2024-12-18 19:42
Thank you very much, you're the best!). I was trying to achieve a translation, which is independent of a region. I was thinking of muting these notifications, but in this case I would have lost an actual useful warning.

**Comment by marcglasberg** [comment] 2024-12-18 21:08
@Apollo108 Could you please try  `i18n_extension: 15.0.0-dev.1` and see if the problem is fixed? You'll have to set the supported locales in the `I18n` widget:

For example, if your app supports American English and Standard Spanish, you'd use: `supportedLocales: [Locale('en', 'US'), Locale('es')]`, or `supportedLocales: ['en-US'.asLocale, 'es'.asLocale]`. And you must add the line `supportedLocales: I18n.supportedLocales` to your `MaterialApp` (or `CupertinoApp`) widget:

```dart
void main() {
    WidgetsFlutterBinding.ensureInitialized();
  
    runApp(I18n(
        initialLocale: ...,
        supportedLocales: ['en-US'.asLocale, 'es'.asLocale], // Here!
        child: AppCore(),
      ));
    }
  }
  
  class AppCore extends StatelessWidget {
    Widget build(BuildContext context) {
      return MaterialApp(
        locale: I18n.locale,
        supportedLocales: I18n.supportedLocales, // Here!
        ...
      ),
  ```

If you provide `I18n.supportedLocales`, only those supported locales will be considered when recording **missing translations**. In other words, unsupported locales will not be recorded as missing translations.

I'm waiting for your feedback, thanks!

**Comment by Apollo108** [comment] 2024-12-19 06:11
It works on Android and iOS, but on the latter, when the language is French, having this console output:

`Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Indexing for request: <WFToolKitIndexingRequest: 0x600001701280>, changeset: .full, priority: 31
Xcode build done.                                            9.3s
Preferred localizations: ["en"]
Connecting to VM Service at ws://127.0.0.1:59129/3DLCx8Tc_oE=/ws
Connected to the VM Service.
Failed to index parameter type: <WFWorkflowPickerParameter: 0x10b777830> in is.workflow.actions.runworkflow: ActionKit.(unknown context at $1be9576cc).WFParameterStateToolKitConversionError.unknownParameterState(WFWorkflowParameterState) for locale: en
Failed to index parameter type: <WFContentArrayParameter: 0x6000075ed970> in is.workflow.actions.list: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFContentArrayParameter) for locale: en
Failed to index parameter type: <WFTagFieldParameter: 0x60000396d6c0> in is.workflow.actions.addnewreminder: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFTagFieldParameter) for locale: en
Failed to index parameter type: <WFSystemShortcutPickerParameter: 0x60000333d5e0> in com.apple.shortcuts.WFShortcutsSmallWidgetConfigurationIntent: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter) for locale: en
Failed to index parameter type: <WFVariableFieldParameter: 0x6000033432a0> in is.workflow.actions.setvariable: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFVariableFieldParameter) for locale: en
Failed to index parameter type: <WFLinkDynamicOptionsEnumerationParameter: 0x10b2732f0> in com.apple.reminders.TTRCreateReminderAppIntent: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.missingLinkParameterContentItem for locale: en
Failed to index parameter type: <WFSSHKeyParameter: 0x600003344f00> in is.workflow.actions.runsshscript: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSSHKeyParameter) for locale: en
Failed to index parameter type: <WFChooseFromMenuArrayParameter: 0x6000075e0b00> in is.workflow.actions.choosefrommenu: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFChooseFromMenuArrayParameter) for locale: en
Failed to index parameter type: <WFPhotoItemCollectionParameter: 0x6000075f29f0> in com.apple.mobileslideshow.PLPhotosReliveWidgetConfigurationIntent: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFPhotoItemCollectionParameter) for locale: en
Failed to index parameter type: <WFSystemShortcutPickerParameter: 0x600003345cc0> in com.apple.shortcuts.WFShortcutsWidgetConfigurationIntent: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter) for locale: en
Failed to index parameter type: <WFExpandingParameter: 0x6000075d4fd0> in is.workflow.actions.encodemedia: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFExpandingParameter) for locale: en
Failed to index parameter type: <WFHomeAccessoryPickerParameter: 0x600003350000> in is.workflow.actions.homeaccessory: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFHomeAccessoryPickerParameter) for locale: en
Failed to index parameter type: <WFDynamicTagFieldParameter: 0x600003990410> in is.workflow.actions.wordpress.post: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFDynamicTagFieldParameter) for locale: en
Failed to index parameter type: <WFDynamicTagFieldParameter: 0x6000039904e0> in is.workflow.actions.wordpress.post: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFDynamicTagFieldParameter) for locale: en
Failed to index parameter type: <WFExpandingParameter: 0x6000075d1c30> in is.workflow.actions.wordpress.post: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFExpandingParameter) for locale: en
Failed to index parameter type: <WFExpandingParameter: 0x6000075ca260> in is.workflow.actions.wordpress.post: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFExpandingParameter) for locale: en
Failed to index parameter type: <WFPosterPickerParameter: 0x600003354d20> in is.workflow.actions.wallpaper.set: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFPosterPickerParameter) for locale: en
Failed to index parameter type: <WFInputTypeParameter: 0x10b72e740> in is.workflow.actions.input: ActionKit.(unknown context at $1be9576cc).WFParameterStateToolKitConversionError.unknownParameterState(WFMultipleValueParameterState) for locale: en
Failed to index parameter type: <WFInputSurfaceParameter: 0x600003354820> in is.workflow.actions.input: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFInputSurfaceParameter) for locale: en
Failed to index parameter type: <WFHomeServicePickerParameter: 0x60000334cbe0> in is.workflow.actions.gethomeaccessorystate: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFHomeServicePickerParameter) for locale: en
Failed to index parameter type: <WFExpandingParameter: 0x6000075a9d90> in is.workflow.actions.downloadurl: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFExpandingParameter) for locale: en
Failed to index parameter type: <WFEvernoteTagsTagFieldParameter: 0x600007beb640> in is.workflow.actions.evernote.new: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFEvernoteTagsTagFieldParameter) for locale: en
Failed to index parameter type: <WFMediaPickerParameter: 0x6000075a25d0> in is.workflow.actions.playmusic: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFMediaPickerParameter) for locale: en
Failed to index parameter type: <WFTableTemplateParameter: 0x600003352300> in is.workflow.actions.conditional: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WorkflowKit.WFTableTemplateParameter) for locale: en
Failed to index parameter type: <WFPosterPickerParameter: 0x60000334da40> in is.workflow.actions.posters.switch: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFPosterPickerParameter) for locale: en
Failed to index parameter type: <WFVariableFieldParameter: 0x60000334dea0> in is.workflow.actions.appendvariable: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFVariableFieldParameter) for locale: en
Failed to index parameter type: <WFSystemShortcutPickerParameter: 0x600003356260> in com.apple.shortcuts.RunShortcutConfigurationIntent: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter) for locale: en
Failed to index parameter type: <WFSystemShortcutPickerParameter: 0x6000033552c0> in com.apple.shortcuts.RunShortcutIntent: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter) for locale: en
Failed to index parameter type: <WFEvernoteTagsTagFieldParameter: 0x600007bd0460> in is.workflow.actions.evernote.get: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFEvernoteTagsTagFieldParameter) for locale: en
Failed to index parameter type: <WFMailSenderPickerParameter: 0x10b274e90> in is.workflow.actions.sendemail: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.missingIntentDescription for locale: en
Failed to index parameter type: <WFFontPickerParameter: 0x600003358000> in is.workflow.actions.overlaytext: (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFFontPickerParameter) for locale: en
Failed to index action parameter: <WFWorkflowPickerParameter: 0x10b777830> due to ActionKit.(unknown context at $1be9576cc).WFParameterStateToolKitConversionError.unknownParameterState(WFWorkflowParameterState)
Failed to index action parameter: <WFContentArrayParameter: 0x6000075ed970> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFContentArrayParameter)
Failed to index action parameter: <WFTagFieldParameter: 0x60000396d6c0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFTagFieldParameter)
Failed to index action parameter: <WFSystemShortcutPickerParameter: 0x60000333d5e0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter)
Failed to index action parameter: <WFVariableFieldParameter: 0x6000033432a0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFVariableFieldParameter)
Failed to index action parameter: <WFLinkDynamicOptionsEnumerationParameter: 0x10b2732f0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.missingLinkParameterContentItem
Failed to index action parameter: <WFSSHKeyParameter: 0x600003344f00> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSSHKeyParameter)
is.workflow.actions.choosefrommenu WFChooseFromMenuAction: Skipped because: [control flow]
Failed to index action parameter: <WFPhotoItemCollectionParameter: 0x6000075f29f0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFPhotoItemCollectionParameter)
Failed to index action parameter: <WFSystemShortcutPickerParameter: 0x600003345cc0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter)
Failed to index action parameter: <WFHomeAccessoryPickerParameter: 0x600003350000> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFHomeAccessoryPickerParameter)
is.workflow.actions.sirikit.donation.handle WFHandleDonatedIntentAction: Skipped because: [donation-based action]
Failed to index action parameter: <WFDynamicTagFieldParameter: 0x600003990410> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFDynamicTagFieldParameter)
Failed to index action parameter: <WFDynamicTagFieldParameter: 0x6000039904e0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFDynamicTagFieldParameter)
Failed to index action parameter: <WFPosterPickerParameter: 0x600003354d20> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFPosterPickerParameter)
Failed to index action parameter: <WFInputTypeParameter: 0x10b72e740> due to ActionKit.(unknown context at $1be9576cc).WFParameterStateToolKitConversionError.unknownParameterState(WFMultipleValueParameterState)
Failed to index action parameter: <WFInputSurfaceParameter: 0x600003354820> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFInputSurfaceParameter)
is.workflow.actions.repeat.count WFFiniteRepeatAction: Skipped because: [control flow]
is.workflow.actions.repeat.each WFForEachRepeatAction: Skipped because: [control flow]
Failed to index action parameter: <WFHomeServicePickerParameter: 0x60000334cbe0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFHomeServicePickerParameter)
Failed to index action parameter: <WFEvernoteTagsTagFieldParameter: 0x600007beb640> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFEvernoteTagsTagFieldParameter)
Failed to index action parameter: <WFMediaPickerParameter: 0x6000075a25d0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFMediaPickerParameter)
is.workflow.actions.conditional WFConditionalAction: Skipped because: [control flow]
Failed to index action parameter: <WFPosterPickerParameter: 0x60000334da40> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFPosterPickerParameter)
Failed to index action parameter: <WFVariableFieldParameter: 0x60000334dea0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFVariableFieldParameter)
Failed to index action parameter: <WFSystemShortcutPickerParameter: 0x600003356260> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter)
is.workflow.actions.useractivity.open WFOpenUserActivityAction: Skipped because: [donation-based action]
Failed to index action parameter: <WFSystemShortcutPickerParameter: 0x6000033552c0> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFSystemShortcutPickerParameter)
Failed to index action parameter: <WFEvernoteTagsTagFieldParameter: 0x600007bd0460> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFEvernoteTagsTagFieldParameter)
Failed to index action parameter: <WFMailSenderPickerParameter: 0x10b274e90> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.missingIntentDescription
Failed to index action parameter: <WFFontPickerParameter: 0x600003358000> due to (extension in ActionKit):__C.WFParameter.ToolKitConversionError.incompatibleParameterType(WFFontPickerParameter)
Indexed: 1023
Errored: 0
Skipped: [control flow: 4, donation-based action: 2]
   control flow: 4
   donation-based action: 2
Finished in 62.187124s
`

**Comment by marcglasberg** [comment] 2024-12-19 16:36
Could you please try the following and tell me the result?

---

For translation to work on iOS you need to add supported locales to `ios/Runner/Info.plist` as described in https://flutter.dev/docs/development/accessibility-and-localization/internationalization#specifying-supportedlocales

Example:

``` 
<key>CFBundleLocalizations</key>
<array>
	<string>en</string>
	<string>fr</string>
</array>
```

**Comment by Apollo108** [comment] 2024-12-19 16:58
Thanks, it works! The console is clear now.

**Comment by Apollo108** [comment] 2024-12-19 17:46
Actually, before adding these strings into Info.plist, this strange output is taking place only once after changing language (both en and fr). After modifying Info.plist, nothing changed - getting similar output once after changing the language. No output after restarting the simulator.

**Comment by marcglasberg** [comment] 2024-12-19 19:27
Ok, I'm closing this issue then. Let me know if any other problem arises. Thanks!

**Closed by marcglasberg** 2024-12-19 19:27 UTC
Labels: enhancement
