### ISSUE TITLE
How to use with po files?

### ISSUE THREAD

**Issue by chriscdn** [marcglasberg/i18n_extension#134] opened 2023-07-31 18:09 UTC
The README.md example uses a `GettextImporter` function, which is imported from `package:i18n_extension/io/import.dart;` This file doesn't exist, which I assume has to do with the v8.0.0 dependency removal on `gettext_parser`.

Can the README.md be updated with a working example with `.po` files?

**Comment by marcglasberg** [comment] 2023-07-31 18:17
Maybe for the time being, try using the previous version before the dependency removal?

**Comment by marcglasberg** [comment] 2023-07-31 18:18
Closing this as duplicate of https://github.com/marcglasberg/i18n_extension/issues/126

**Closed by marcglasberg** 2023-07-31 18:18 UTC

**Comment by chriscdn** [comment] 2023-08-01 09:24
I'm using an older version, but it forces me to use an older version of Flutter due to a dependency conflict (I think with the `intl` package).

**Comment by marcglasberg** [comment] 2023-08-05 23:31
You can specify your `intl` version in your `pubspec.yaml` file:

```
dependency_overrides:
  intl: ^0.18.1
```
